encryption: encryption.c
	gcc -o encryption -Wall -Werror -pedantic -std=gnu99 encryption.c
initArray: initArray.c
	gcc -o initArray -Wall -Werror -pedantic -std=gnu99 initArray.c
fgetc: fgetc.c
	gcc -o fgetc -Wall -Werror -pedantic -std=gnu99 fgetc.c
fgets: fgets.c
	gcc -o fgets -Wall -Werror -pedantic -std=gnu99 fgets.c
WritingProducts: WritingProducts.c
	gcc -o WritingProducts -Wall -Werror -pedantic -std=gnu99 WritingProducts.c
